#!/bin/bash

if [ ! "$1" ]; then
	exit
fi

changeStuff() {
	sed \
		-r -e "s/([^A-Z-])([A-Z\(])/\1 \2/g" \
		-r -e "s/([^'])([0-9])/\1 \2/g" \
		-r -e "s/('[0-9])/ \1/g" \
		-e 's/[(][^)]*[)]//g' \
		-e "s/ \././g" \
		| tr -s ' '
}
#		-e 's/|/-/g' \
#		-e 's/\[[^][]*\]//g' \
#		-e "s/([^()]*)//g"  \

for o in *.$1 ; do
#	n="$(sed -r -e "s/([^A-Z])([A-Z])/\1 \2/g" <<< "$o")"
	#n="$(sed -e "s/([^()]*)//g" -r -e "s/([^A-Z])([A-Z\(])/\1 \2/g" <<< "$o")"
	#n="$(sed -e 's/\[[^][]*\]//g' -e "s/([^()]*)//g" -r -e "s/([^A-Z])([A-Z\(])/\1 \2/g" <<< "$o")"
	n="$(changeStuff <<< "$o")"
#	echo -e "$o\n	-> $n"
#	s/([^()]*)//g;
	mv -vi "$o" "$n"
done
